language: rust

matrix:
  include:
    - rust: stable
      script:
        - cargo test
        - cargo build

    - rust: nightly
      script:
        - cargo test
        - cargo build

    - rust: nightly
      name: Clippy
      script:
        - rustup component add clippy || travis_terminate 0
        - cargo clippy -- -D clippy::all

  allow_failures:
    - rust: nightly
      name: Clippy

script:
  - cargo test
  - cargo build
